# Really broken package
pack   age:
  name: 'broken-package-yf'
  descri   p ti on: 'A broken package'
  ve
  
  rsio n: 0.1.0
  url: 'https://github.com/JakeRoggenbuck/broken-package-yf'

  aut    hors:
    - 'Jake Roggenbuck'

  license: 'MIT'

depends:
